FIND_PATH(ZLIB_COMPLETE_INCLUDE_DIR zlc/zlibcomplete.hpp /usr/include /usr/local/include)

FIND_LIBRARY(ZLIB_COMPLETE_LIBRARY NAMES zlibcomplete PATHS /usr/lib /usr/local/lib)

MARK_AS_ADVANCED(ZLIB_COMPLETE_LIBRARY)
MARK_AS_ADVANCED(ZLIB_COMPLETE_INCLUDE_DIR)


IF (ZLIB_COMPLETE_INCLUDE_DIR AND ZLIB_COMPLETE_LIBRARY)
   SET(ZLIB_COMPLETE_FOUND TRUE)
ENDIF (ZLIB_COMPLETE_INCLUDE_DIR AND ZLIB_COMPLETE_LIBRARY)


IF (ZLIB_COMPLETE_FOUND)
   IF (NOT ZLIB_COMPLETE_FIND_QUIETLY)
      MESSAGE(STATUS "Found ZlibComplete: ${ZLIB_COMPLETE_LIBRARY}")
   ENDIF (NOT ZLIB_COMPLETE_FIND_QUIETLY)
ELSE (ZLIB_COMPLETE_FOUND)
   IF (ZLIB_COMPLETE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find lzlibcomplete - https://github.com/rudi-cilibrasi/zlibcomplete")
   ELSE (ZLIB_COMPLETE_FIND_REQUIRED)
      MESSAGE(STATUS "ZlibCoplete not found - https://github.com/rudi-cilibrasi/zlibcomplete")
   ENDIF (ZLIB_COMPLETE_FIND_REQUIRED)
ENDIF (ZLIB_COMPLETE_FOUND)
